### ISSUE TITLE
ParquetDataset raise ValueError: No supported fields found in parquet file

### ISSUE THREAD

**Issue by welsonzhang** [DeepRec-AI/DeepRec#582]
Problem:
    使用MapReduce生成对应的Parquet存储，但是使用DeepRec的ParquetDataset 抛异常了，异常如下：
    No supported fields found in parquet file。
    对应的parquet的schema格式如下：
    `message example {required int32 id;required binary email;}`
    使用的MR任务参考：https://github.com/whale2/iow-hadoop-streaming
原因：
   走读代码发现没法扫描footer里面的schema，导致抛异常了。为什么没法获取schema呢？

排查步骤：
   (1)  自己用python代码是可以顺利读取对应的schema的。
   (2)  放弃mr，使用python代码生成类似的结构的内容，ParquetDataset 是可以顺利读出来的。
   (3)  对比MR生成的parquest和python本地生成的parquet格式发现，一个是bytes，一个是string。
   (4)  因此怀疑是MR生成的parquet是bytes格式，导致DeepRec没法识别。

最终将schema定义成如下，问题解决：
    `message example {required int32 id;required binary email(UTF-8);}`

**Comment by JackMoriarty** [comment]
Thanks for submitting issue. This problem is fixed by PR #850
