### ISSUE TITLE
[Doc] Contributer CLA link has expired 

### ISSUE THREAD

**Issue by StevenShi-23** [DeepRec-AI/DeepRec#813]
The DeepRec docs are open source! To get involved, read the user documents: https://deeprec.readthedocs.io/en/latest/index.html

**URL(s) with the issue**

Both individual and corporate Contributor License Agreement (CLA) links have expired. See https://github.com/DeepRec-AI/DeepRec/blob/3bc930a5cd7c46c646a2f1c4bfc40282ff9de053/CONTRIBUTING.md

**Description of issue (what needs changing)**

Would be great if we can update the link so as to allow other people to contribute.

**Comment by liutongxuan** [comment]
DeepRec already contribute to Linux Foundation AI & Data. We follow LFAI's suggestion to use DCO replace CLA.

Please check the latest CONTRIBUTING.md.

Fixed PR: https://github.com/DeepRec-AI/DeepRec/pull/847
