### ISSUE TITLE
How to use workqueue?

### ISSUE THREAD

**Issue by zhoujingzhe** [DeepRec-AI/DeepRec#830]
using modelzoo/simple_multitask as an example.

If launch a training program with "python train.py", there are lots of logs like "loss=0.606937, steps=1".
However, if launch a training program with "python train.py --workqueue=True", there are only one info "loss=0.606937, steps=1".

In the log![image](https://user-images.githubusercontent.com/17643399/233901912-e7487438-68a2-45c1-b849-1847af1b43cf.png)
why restore work queue twice? Especially after training completed?

**Comment by liutongxuan** [comment]
good catch, there's bug in the modelzoo/simple_multitask. We have fix it with the PR: https://github.com/DeepRec-AI/DeepRec/pull/839
