### ISSUE TITLE
feature_column.sparse_column_wth_embedding wrong name

### ISSUE THREAD

**Issue by Tianna-Liu** [DeepRec-AI/DeepRec#842]
The DeepRec docs are open source! To get involved, read the user documents: https://deeprec.readthedocs.io/en/latest/index.html

**URL(s) with the issue**

**Description of issue (what needs changing)**

![image](https://user-images.githubusercontent.com/18749879/235081025-70686591-b27d-4064-aec5-b6ada7098e8f.png)
https://deeprec.readthedocs.io/zh/latest/Feature-Eviction.html

**Comment by liutongxuan** [comment]
good catch, @Tianna-Liu can you submit a fix about the issue?

**Comment by liutongxuan** [comment]
fixed, https://github.com/DeepRec-AI/DeepRec/pull/844
