### ISSUE TITLE
crosstool_wrapper_driver_is_not_gcc   【 builf failed】

### ISSUE THREAD

**Issue by Lvjinhong** [DeepRec-AI/DeepRec#843]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04):   
- DeepRec version or commit id:  2c97172bc55ea0348f3add758551d9a0db0b9e46
- Python version:3.8.10
- Bazel version (if compiling from source): 5.3.1
- GCC/Compiler version (if compiling from source):9.4
- CUDA/cuDNN version: 11.6.2

**Describe the problem**
The image source used is alideeprec/deeprec-base:deeprec-base-gpu-py38-cu116-ubuntu20.04. During the process of building with bazel, I encountered some unexpected issues. After attempting to pull the image, installing bazel and configuring the build file, I started to encounter errors.

First, there was an error related to escape sequences in the nccl file, which caused confusion. I replaced the backslashes with double backslashes and continued with the build
![image](https://user-images.githubusercontent.com/96970081/235329701-4ea1bb48-d7de-41b8-af3c-27275a623724.png)

 However, I then encountered another error  “  crosstool_wrapper_driver_is_not_gcc   “ that has been troubling me for a long time. Adding the flag "--cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0"" did not solve the issue. Currently, this is the problem I am facing.
![img_v2_67f5b991-6fb9-4394-8a11-a9861c7d8a4g](https://user-images.githubusercontent.com/96970081/235329812-2a0c5135-9b6f-4e8f-978c-37984a03c703.jpg)

**Any other info / logs**
this is my config

build --action_env PYTHON_BIN_PATH="/usr/bin/python"
build --action_env PYTHON_LIB_PATH="/usr/lib/python3/dist-packages"
build --python_path="/usr/bin/python"
build:xla --define with_xla_support=true
build --config=xla
build:parquet_dataset --define with_parquet_dataset_support=true
build:api_compatible --define with_api_compatible=true
build --action_env TF_USE_CCACHE="0"
build --action_env CUDA_TOOLKIT_PATH="/usr/local/cuda"
build --action_env TF_CUDA_COMPUTE_CAPABILITIES="8.0"
build --action_env LD_LIBRARY_PATH="/usr/local/nvidia/lib:/usr/local/nvidia/lib64"
build --action_env GCC_HOST_COMPILER_PATH="/usr/bin/gcc"
build --config=cuda
build:opt --copt=-march=native
build:opt --copt=-Wno-sign-compare
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
build:v2 --define=tf_api_version=2
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test --test_tag_filters=-benchmark-test,-no_oss,-oss_serial
test --build_tag_filters=-benchmark-test,-no_oss
test --test_tag_filters=-gpu
test --build_tag_filters=-gpu
build --action_env TF_CONFIGURE_IOS="0"

and  run shell：

bazel build  --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0"--verbose_failures    -c opt   --config=v1 --config=cuda  --config=opt  //tensorflow/tools/pip_package:build_pip_package

Include any logs or source code that would be helpful to diagnose the problem.

**Comment by zzhong44** [comment]
Hello, did you resolve this problem?
