### ISSUE TITLE
r1.15.5-deeprec2302版编译报错

### ISSUE THREAD

**Issue by supercocoa7654** [DeepRec-AI/DeepRec#863]
镜像用的deeprec-dev-cpu-py38-ubuntu20.04

ERROR: /home/DeepRec-r1.15.5-deeprec2302/tensorflow/core/kernels/BUILD:4043:1: C++ compilation of rule '//tensorflow/core/kernels:matmul_op' failed (Exit 1)
In file included from ./tensorflow/core/framework/register_types.h:22,
                 from ./tensorflow/core/kernels/matmul_op_impl.h:27,
                 from tensorflow/core/kernels/matmul_op_complex.cc:16:
./tensorflow/core/framework/variant.h: In member function 'void tensorflow::Variant::HeapOrInline::ResetMemory()':
./tensorflow/core/framework/variant.h:653:45: warning: 'void* memset(void*, int, size_t)' clearing an object of type 'union tensorflow::Variant::HeapOrInline' with no trivial copy-assignment; use value-initialization instead [-Wclass-memaccess]
  653 |       this, 0, sizeof(Variant::HeapOrInline));
      |                                             ^
./tensorflow/core/framework/variant.h:496:9: note: 'union tensorflow::Variant::HeapOrInline' declared here
  496 |   union HeapOrInline {
      |         ^~~~~~~~~~~~
gcc: fatal error: Killed signal terminated program cc1plus
compilation terminated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2328.893s, Critical Path: 233.69s
INFO: 3604 processes: 3604 local.
FAILED: Build did NOT complete successfully

**Comment by liutongxuan** [comment]
It seems there's not enough memory to build (too much build jobs), please use --job to limit the parallel build jobs.
